# Generated by Django 4.2.7 on 2023-11-11 14:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='des',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
